# Generated by Django 5.2.11 on 2026-03-22 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('township_properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TownshipObjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objector_status', models.CharField(choices=[('owner', 'Owner'), ('not_owner', 'Not Owner'), ('municipality', 'Municipality'), ('auth_representative', 'Authorized Representative')], max_length=30)),
                ('auth_rep_attachment', models.FileField(blank=True, null=True, upload_to='objections/attachments/')),
                ('not_owner_description', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=50)),
                ('companyreg', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_address', models.CharField(max_length=255)),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_home', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_work', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_mobile', models.CharField(max_length=20)),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('incorrect_valuation', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('omitted_property', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('incorrect_owner_name', models.BooleanField(default=False)),
                ('incorrect_category_rating', models.BooleanField(default=False)),
                ('incorrect_extent', models.BooleanField(default=False)),
                ('incorrect_physical_address', models.BooleanField(default=False)),
                ('incorrect_postal_address', models.BooleanField(default=False)),
                ('rates_query', models.BooleanField(default=False)),
                ('property_description', models.CharField(max_length=255)),
                ('property_physical_address', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('extent', models.CharField(max_length=50)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('owner', models.CharField(db_index=True, max_length=20)),
                ('objection_attachment', models.FileField(upload_to='objections/docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('township_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='township_properties.townshipproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
