# Generated by Django 5.2.11 on 2026-03-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='townshipobjection',
            options={'verbose_name': 'Township Objection', 'verbose_name_plural': 'Towship Objections'},
        ),
        migrations.AddField(
            model_name='townshipobjection',
            name='objection_number',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
