# Generated by Django 5.2.11 on 2026-03-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0003_farmobjection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='townshipobjection',
            options={'verbose_name': 'Township Objection', 'verbose_name_plural': 'Township Objections'},
        ),
    ]
