# Generated by Django 5.2.11 on 2026-03-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0004_alter_townshipobjection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmobjection',
            name='objection_attachment',
            field=models.FileField(upload_to='objections/farms/docs/'),
        ),
    ]
