# Generated by Django 5.2.11 on 2026-03-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0005_alter_farmobjection_objection_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmobjection',
            name='auth_rep_attachment',
            field=models.FileField(blank=True, null=True, upload_to='objections/auth_rep/attachments/'),
        ),
        migrations.AlterField(
            model_name='townshipobjection',
            name='auth_rep_attachment',
            field=models.FileField(blank=True, null=True, upload_to='objections/auth_rep/attachments/'),
        ),
        migrations.AlterField(
            model_name='townshipobjection',
            name='objection_attachment',
            field=models.FileField(upload_to='objections/township/docs/'),
        ),
    ]
