# Generated by Django 5.2.11 on 2026-03-25 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0007_alter_farmobjection_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmobjection',
            name='auth_rep_attachment',
        ),
        migrations.RemoveField(
            model_name='townshipobjection',
            name='auth_rep_attachment',
        ),
        migrations.RemoveField(
            model_name='townshipobjection',
            name='objection_attachment',
        ),
        migrations.CreateModel(
            name='FarmsAuthRepAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='objections/farms/authrep')),
                ('auth_rep_attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_rep_attachments', to='objections.farmobjection')),
            ],
        ),
        migrations.CreateModel(
            name='FarmsObjectionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='objections/farms/objections')),
                ('farms_objection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms_obection_attachments', to='objections.farmobjection')),
            ],
        ),
        migrations.CreateModel(
            name='TownshipAuthRepAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='objections/townships/authrep')),
                ('auth_rep_attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_rep_attachments', to='objections.townshipobjection')),
            ],
        ),
        migrations.CreateModel(
            name='TownshipObjectionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='objections/townships/objections')),
                ('township_objection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='township_objection_attachments', to='objections.townshipobjection')),
            ],
        ),
    ]
