# Generated by Django 5.2.11 on 2026-03-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objections', '0008_remove_farmobjection_auth_rep_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmobjection',
            name='objection_attachment',
        ),
    ]
