# Generated by Django 5.2.11 on 2026-02-28 00:10

import django.core.validators
import property_search.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, db_index=True, help_text='Enter a valid South African ID number (13 digits).', max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(13, message='ID number must be exactly 13 digits.'), django.core.validators.RegexValidator('^\\d{13}$', message='ID number must consist of 13 digits only.')], verbose_name='South African ID Number')),
                ('sg_code_21', models.CharField(db_index=True, max_length=21, validators=[property_search.models.validate_sg_code_21])),
                ('registered_owner', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('min_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('grv', models.CharField(db_index=True, max_length=50)),
                ('regdiv', models.CharField(db_index=True, max_length=50)),
                ('farm_name', models.CharField(db_index=True, max_length=100)),
                ('sectional_title', models.CharField(blank=True, max_length=100, null=True)),
                ('erf_no', models.CharField(db_index=True, max_length=50)),
                ('ptn', models.CharField(db_index=True, max_length=10)),
                ('unit', models.CharField(db_index=True, max_length=10)),
                ('extent', models.CharField(max_length=50)),
                ('ha', models.CharField(max_length=50)),
                ('physical_address', models.CharField(db_index=True, max_length=255)),
                ('owner', models.CharField(db_index=True, max_length=20)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('owner_status', models.CharField(db_index=True, max_length=20)),
                ('category', models.CharField(db_index=True, max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
