# Generated by Django 5.2.11 on 2026-03-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_search', '0002_remove_farmproperty_registered_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmproperty',
            options={'verbose_name': 'Farm Property', 'verbose_name_plural': 'Farm Properties'},
        ),
        migrations.AddIndex(
            model_name='farmproperty',
            index=models.Index(fields=['sg_code_21'], name='property_se_sg_code_ad8184_idx'),
        ),
    ]
