# Generated by Django 5.2.11 on 2026-03-10 17:23

import django.core.validators
import township_properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TownshipProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, db_index=True, help_text='Enter a valid South African ID number (13 digits).', max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(13, message='ID number must be exactly 13 digits.'), django.core.validators.RegexValidator('^\\d{13}$', message='ID number must consist of 13 digits only.')], verbose_name='South African ID Number')),
                ('sg_code_21', models.CharField(db_index=True, max_length=21, validators=[township_properties.models.validate_sg_code_21])),
                ('prop_class', models.CharField(db_index=True, max_length=50)),
                ('township', models.CharField(db_index=True, max_length=50)),
                ('township_name_ext', models.CharField(db_index=True, max_length=100)),
                ('sectional_tittle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('erf_no', models.CharField(db_index=True, max_length=50)),
                ('portion_no', models.CharField(db_index=True, max_length=10)),
                ('unit_no', models.CharField(db_index=True, max_length=10)),
                ('registered_owner', models.CharField(db_index=True, max_length=100)),
                ('street_address', models.CharField(db_index=True, max_length=255)),
                ('extent', models.CharField(max_length=50)),
                ('ext', models.CharField(max_length=50)),
                ('owner_status', models.CharField(db_index=True, max_length=20)),
                ('category', models.CharField(db_index=True, max_length=30)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
