# Generated by Django 5.2.11 on 2026-03-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('township_properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='townshipproperty',
            options={'verbose_name': 'Township Property', 'verbose_name_plural': 'Towship Properties'},
        ),
        migrations.AddIndex(
            model_name='townshipproperty',
            index=models.Index(fields=['sg_code_21'], name='township_pr_sg_code_1b173b_idx'),
        ),
    ]
